# Generated by Django 4.2.3 on 2023-09-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя предмета')),
                ('lesson_time', models.CharField(choices=[('8:00-8:45', '8:00-8:45'), ('8:50-9:35', '8:50-9:35'), ('9:40-10:25', '9:40-10:25'), ('10:30-11:15', '10:30-11:15'), ('11:20-12:05', '11:20-12:05')], max_length=100, verbose_name='Время уроков')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.TextField(max_length=200, verbose_name='Домашнее задание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('link', models.URLField(verbose_name='Полезные ссылки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
